spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/to_do_list
    username: postgres
    password: sonic912
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

